In [1]:
from tensorflow.keras.preprocessing.text import one_hot

C:\Users\sampath.manchala\AppData\Roaming\Python\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\sampath.manchala\AppData\Roaming\Python\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\sampath.manchala\AppData\Roaming\Python\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framewo

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3521, 6323, 5022, 8020],
 [3521, 6323, 5022, 922],
 [3521, 2643, 5022, 6427],
 [1476, 4049, 9555, 4404, 558],
 [1476, 4049, 9555, 4404, 8430],
 [2631, 3521, 3878, 5022, 1436],
 [2916, 7760, 7900, 4404]]

In [5]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3521 6323 5022 8020]
 [   0    0    0    0 3521 6323 5022  922]
 [   0    0    0    0 3521 2643 5022 6427]
 [   0    0    0 1476 4049 9555 4404  558]
 [   0    0    0 1476 4049 9555 4404 8430]
 [   0    0    0 2631 3521 3878 5022 1436]
 [   0    0    0    0 2916 7760 7900 4404]]


In [9]:
## feature representation
dim=10

In [16]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_shape=(sent_length,)))
model.compile('adam','mse')

C:\Users\sampath.manchala\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [17]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step


array([[[ 0.01527966,  0.03207859, -0.01645702, -0.01550479,
         -0.00923584, -0.02942979, -0.03418909,  0.0455805 ,
          0.02645412, -0.01073222],
        [ 0.01527966,  0.03207859, -0.01645702, -0.01550479,
         -0.00923584, -0.02942979, -0.03418909,  0.0455805 ,
          0.02645412, -0.01073222],
        [ 0.01527966,  0.03207859, -0.01645702, -0.01550479,
         -0.00923584, -0.02942979, -0.03418909,  0.0455805 ,
          0.02645412, -0.01073222],
        [ 0.01527966,  0.03207859, -0.01645702, -0.01550479,
         -0.00923584, -0.02942979, -0.03418909,  0.0455805 ,
          0.02645412, -0.01073222],
        [-0.04980841,  0.02561234, -0.03753318,  0.04194316,
         -0.00388163,  0.04024625, -0.03026583,  0.00351164,
         -0.01253333,  0.02820127],
        [-0.00374501, -0.0050763 ,  0.04285901,  0.04812059,
         -0.02016295,  0.02682041, -0.04566428,  0.03069863,
          0.01839062,  0.04168488],
        [ 0.02225906, -0.02519244, -0.00794375,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6186, 6775,  637, 4895])

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 19ms/step


array([[ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [-0.03792738,  0.01958679, -0.04232483, -0.03475742,  0.02182527,
         0.01143194, -0.03125288,  0.02584182,  0.0050171 ,  0.04725457],
       [-0.02213118,  0.00730393,  0.02797868, -0.02386508, -0.0024281 ,
         0.04419583, -0.02011771, -0.00502002, -0.03373672, -0.04126013],
       [-0.02629154,  0.02487988, -0.02824695,  0.0302802 , -0.01835672,
        -0.00683415,  0.01606056, -0.04426531